config/routes.rb
Rails.application.routes.draw do

  resources :tickets
  resources :inventories
  resources :orderlines
  resources :orders
  resources :products
  resources :beverages
  resources :timetables
  resources :chairs
  resources :movies
  resources :theaters
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'login', to: 'account#login'
  post 'login', to: 'account#check_login'
  get 'register', to: 'account#register'
  post 'register', to: 'account#create_user'
  get 'logout', to: 'account#logout'

  get 'main', to: 'main#main'
  get 'timetable/:name', to: 'main#show_timetable', as: 'showtime'
  post 'buyticket', to: 'main#buy_ticket'
  get 'ordersummary', to: 'main#order_summary'
  post 'addticket', to: 'main#post_add_ticket'
  get 'createorder', to: 'main#create_order'
  get 'buybeverage', to: 'main#buy_beverage'
  post 'addbeverage', to: 'main#post_add_beverage'
  get 'myorder', to: 'main#show_my_order'

end

app/controllers/main_controller.rb
class MainController < ApplicationController
	include MainConcern

	before_action :set_user, only: %i[ order_summary create_order show_my_order]
	before_action :clear_all_session, only: %i[ main show_timetable]
	before_action :require_order, only: %i[order_summary]
	
	def main
		@movies = Movie.get_now_showing
		@movies += Movie.get_coming_soon
	end

	def show_timetable
		@movie = Movie.find_by(name: params[:name])
		@timetables = @movie.get_timetable
		@empty = true
		#@timetables = Timetable.where(movie: @movie).order('time_start')
	end

	def buy_ticket
		if params[:timetable] == ""
			redirect_to main_path
		else
			@timetable = Timetable.find(params[:timetable])
			session[:timetable_id] = @timetable.id
			@movie = Movie.find(@timetable.movie_id)
			@movie_name = Movie.find(@timetable.movie_id).name
			session[:timetable] = params[:timetable]
			@theater = Theater.find(@timetable.theater_id)
			# puts "--------------------------"
			# puts @theater.name
			@row = @theater.row
			@column = @theater.column
			gon.timetable = @timetable
			gon.sold_row = @timetable.sold_row
			gon.sold_col = @timetable.sold_col
			gon.row = @row
			gon.col = @column
			gon.chair_type = @theater.get_chair_type
			@chairs_detail = @theater.get_chair_detail
			gon.seat = nil
			if session[:seat] != nil
				gon.seat = session[:seat]
			end
		end
	end


	def post_add_ticket
		session[:seat] = params[:seat]
		session[:timetable] = params[:timetable]
		redirect_to buybeverage_path
		# render :js => "window.location = '/ordersummary'"
		# puts params[:seat]
		# puts session[:seat]
	end

	def order_summary

		if session[:timetable] != nil
			@movie = Movie.find(session[:timetable]["movie_id"])
			@theater = Theater.find(session[:timetable]["theater_id"])
		end
		@selected_seat = Array.new

		if session[:seat] != nil
			session[:seat].each do |key, value| # value-> [row, col, type]
				@selected_seat.append( [(value[0].to_i+64).chr + value[1].to_s, value[2] ])
			end
		end

		gon.seat = @selected_seat
		gon.beverage = session[:beverage]
		gon.timetable = session[:timetable]
		@total_price = 0
	end

	def create_order
		order = Order.create(user: @user)
		if session[:seat] != nil
			timetable = Timetable.find(session[:timetable]["id"].to_i)
			session[:seat].each do |key, value|
				seat = Chair.find_by(row: (value[0].to_i+64).chr, column: value[1].to_i, theater_id: timetable.theater_id)
				ticket = Ticket.create(timetable: timetable, chair: seat)
				Orderline.create(order: order, quantity: 1, ticket: ticket, isticket: true, totalPrice: seat.price)
			end
		end

		if session[:beverage] != nil
			session[:beverage].each do |key, value|
				beverage = Beverage.find_by(name: value[0])
				Orderline.create(order: order, quantity: value[1].to_i, beverage: beverage, isticket: false, totalPrice: value[1].to_i*value[2].to_i)
			end
		end
		redirect_to main_path, flash:{success: "buy successfully"}
	end

	def buy_beverage
		@beverages = Beverage.all
		gon.beverages = @beverages
		if session[:beverage] != nil
			gon.selected_beverages = session[:beverage]
		end
	end

	def post_add_beverage
		session[:beverage] = params[:beverage]
		redirect_to ordersummary_path
	end

	def show_my_order
		@orders = @user.get_all_order
		# puts @orders

	end

	private
    # Use callbacks to share common setup or constraints between actions.
    def set_user

    	if session[:user_id] != nil 
	      @user = User.find(session[:user_id])
	    else 
	    	redirect_to login_path, flash:{alert: "Please login"}
	    end
    end

    def clear_all_session
    	id = session[:user_id]
    	f = flash
    	session.clear
		session[:user_id] = id
		flash = f
    end

    def require_order
		if session[:seat] == nil and session[:beverage] == nil
			redirect_to main_path, flash:{notice: "please select seat or beverage"}
		end
    end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/_beverageCard.html.haml
.card.border-secondary.mb-3
  = image_tag "#{beverage.name}.jpg", class: 'card-img-top'
  .card-header.fs-4
    = beverage.name
  .card-body
    %p.card-text.fs-6
      Price: 
      = beverage.price
  .card-footer
    %p.card-text.fs-6
      %input.form-control{:type => "text", id: "#{beverage.name}"}

app/views/main/_beverageCardSummary.html.haml
.card.border-secondary.mb-3
  .card-header.fs-4
    = name
  .card-body
    %p.card-text.fs-6
      quantity: 
      = amount
      &nbsp;
      price:
      = price
  .card-footer
    %p.card-text.fs-6
      total price:
      = price*amount
      - @total_price += price*amount
      / - puts @total_price

app/views/main/_movieCard.html.haml
.card.border-secondary.mb-3
  / %img.card-img-top{src: "#{movie.name}.jpg"}
  = image_tag "#{movie.name}.jpg", class: 'card-img-top', height: 613
  .card-header.fs-4
    = movie.name
  .card-body
    %p.card-text.fs-6 
      Duration 
      = movie.duration
      minutes
  .card-footer
    - if movie.date_in < Date.today
      %a.card-text
        = link_to 'buy ticket', controller: "main", action: "show_timetable", name: movie.name
    - elsif movie.date_in > Date.today
      %p.card-text.fs-6 
        coming soon

app/views/main/_movieCardDetail.html.haml
.card.border-secondary.mt-5.fs-6
  .card-body.fs-6
    Type: 
    = @movie.description
  .card-body
    %p.card-text.fs-6
      Duration 
      = @movie.duration
      minutes
  .card-body
    %p.card-text.fs-6
      Date in: 
      = @movie.date_in
  .card-body
    %p.card-text.fs-6
      Date out: 
      = @movie.date_out

app/views/main/_ticketCardSummary.html.haml
.card.border-secondary.mb-3
  .card-header.fs-4
    = @movie.name
  .card-body.fs-6
    Cinema: 
    = @theater.name
    &nbsp;
    Seat: 
    = seat
    &nbsp;
    Date:
    = session[:timetable]["time_start"].to_date
    &nbsp;
    Time: 
    = session[:timetable]["time_start"][11, 5]
    - #.strftime("%H:%M")[0]
    &nbsp;
    Type: 
    = type
  .card-footer
    %p.card-text.fs-6
      total price: 
      - price = Chair.get_price(@theater, type)
      = price
      - @total_price += price 
      / - puts @total_price

app/views/main/buy_beverage.html.haml
%h1 Buy Beverage
%p 
	.row.row-cols-1.row-cols-md-3.g-4
		- @beverages.each do |beverage|
			.col
				= render "beverageCard", beverage: beverage
	.row.justify-content-between
		.col-1
			= button_to "back", buyticket_path, method: "post", class: "btn btn-secondary btn-lg mt-5", params: {timetable: session[:timetable_id]}
		.col-1
			%button.btn.btn-primary.btn-lg.mt-5{id: "btn-next"}
				next

:javascript
		console.log(gon.beverages)
		console.log(gon.selected_beverages)

		for (let key in gon.selected_beverages) {
			let id = "#" + gon.selected_beverages[key][0]
			console.log(id)
			$(id).val(gon.selected_beverages[key][1])
		}

		$("#btn-next").click(function(){
			console.log("next button")
			let selected_beverage = [];
			for (let i = 0;i < gon.beverages.length;i++) {
				id = "#" + gon.beverages[i].name
				console.log(id)
				console.log($(id).val())
				let amount = parseInt($(id).val());
				if(amount > 0) {
					selected_beverage.push([gon.beverages[i].name, amount, gon.beverages[i].price])
				}
			}
			console.log(selected_beverage)
			$.ajax({
				url: "/addbeverage",
				type: "POST",
				data: {beverage: selected_beverage}	
			});
		});

app/views/main/buy_ticket.html.haml
%p
	.row.align-items-end.justify-content-center
		.col-lg-3.col-md-5.col-sm-12
			= image_tag "#{@movie.name}.jpg", height: 300 
		.col-lg-9.col-md-7.col-sm-12.mt-3
			%p.fs-2.spc
				= @movie.name
				&nbsp;
				= "Cinema: #{@theater.name}"
				&nbsp;
				= "Start: #{@timetable.time_start.strftime("%H:%M")} @ #{@timetable.time_start.to_date}"
			= render "movieCardDetail"
%p
	.row.align-items-center.justify-content-center
		- @chairs_detail.each do |type, price|
			- if type == "premium"
				- c = "btn-primary"
				- p = price
			- elsif type == "normal"
				- c = "btn-info"
				- p = price
			.col-1.d-flex.justify-content-center{:style => "display: flex; flex-direction: column;"}
				%div
					%button{class: "btn #{c} disabled"} X
				%div.fs-6.mt-1
					= "#{p} B"

%p
	.container
		- for i in 1..@row do
			.row.align-items-center
				- for j in 1..@column do
					- if j == 1
						.col-md-auto.fs-4
							= (i+64).chr
					.col.d-flex.justify-content-center
						%button.btn.btn-lg.mt-3.btn-seat{id: "#{i}-#{j}",:type => "button", "data-row": i, "data-col": j, "data-type": ""} 
							= j
		.row.mt-3
			%button.btn.btn-secondary.disabled.d-grid.gap-2 SCREEN
		.row.justify-content-between
			.col-3
				= button_to "back", showtime_url(name: @movie_name), method: "get", class: "btn btn-secondary btn-lg mt-5"
			.col-3
				%button.btn.btn-primary.btn-lg.mt-5{id: "btn-next"}
					next

:javascript
	let selected_seat = [];
	console.log(gon.chair_type)
	// first loop set type of chair -> premium and standard
	for (let i = 1;i <= gon.row;i++) {
		for (let j = 1;j <= gon.col;j++) {
			let id = "#" + i + "-" + j
			console.log(id)
			if (gon.chair_type[(i-1)*gon.col + (j-1)] == "premium") {
				console.log("premium")
				$(id).addClass("btn-primary")
				$(id).attr("data-type", "premium")
			} else if (gon.chair_type[(i-1)*gon.col + (j-1)] == "normal") {
				$(id).addClass("btn-info")
				$(id).attr("data-type", "normal")
			}
		}
	}

	//second loop set availibility of chair -> sold or not
	for (let i = 0;i < gon.sold_row.length;i++){
		let id = "#" + (gon.sold_row[i].charCodeAt(0) - 64) + "-" + gon.sold_col[i]
		$(id).removeClass("btn-primary")
		$(id).removeClass("btn-info")
		$(id).addClass("btn-secondary")
		$(id).addClass("disabled")		
	}

	//click button to select
	$(".btn-seat").click(function(){
		console.log("click!")
		let row = $(this).attr("data-row")
		let col = $(this).attr("data-col")
		if(! $(this).hasClass("btn-sedondary")) {
			if ($(this).hasClass("selected")) {
				$(this).removeClass("selected")
				selected_seat = selected_seat.filter(function(item){ return item[0] != row || item[1] != col})
				console.log(selected_seat)
				console.log("unselected")
			} else {
				$(this).addClass("selected")
				selected_seat.push([row, col, $(this).attr("data-type")])
				console.log("selected")
				console.log(selected_seat)
			}
		} 		

	});	

	for (let key in gon.seat) {
		let id = "#" + gon.seat[key][0] + "-" + gon.seat[key][1]
		console.log(id)
		$(id).click()
	}

	$("#btn-next").click(function(){
		console.log(selected_seat)
		$.ajax({
			url: "/addticket",
			type: "POST",
			data: {seat: selected_seat, timetable: gon.timetable}	
		});
	});

/ secondary -> sold
/ primary -> premium
/ info -> standard
/ .selected -> selected

app/views/main/main.html.haml
%h1 MainPage
%p 
	.row.row-cols-1.row-cols-md-3.g-4
		- if @movies.any?
			- @movies.each do |movie|
				.col
					=render "movieCard", movie: movie
		- else
			no movies showing now, please comeback later.

app/views/main/order_summary.html.haml
%h1 order summary

%p 
	-# puts @selected_seat
	- if @selected_seat != nil
		-@selected_seat.each do |seat, type|
			= render "ticketCardSummary", seat: seat, type: type
	- if session[:beverage] != nil
		-session[:beverage].each do |key, value|
			= render "beverageCardSummary", name: value[0], amount: value[1].to_i, price: value[2].to_i
%p
	.row.justify-content-between.align-items-center.mt-5
		.col
			.fs-4
				TOTAL PRICE: 
				= @total_price
	.row.justify-content-between
		.col-3
			= button_to "back", buybeverage_path, method: "get", class: "btn btn-secondary btn-lg mt-5"
		.col-1
			= link_to "confirm", createorder_path,class: "btn btn-primary btn-lg mt-5"

app/views/main/show_my_order.html.haml
%h1 My Order
%table.table#index
	%thead
		%tr
			%th Order Number
			%th Name
			%th Quantity
			%th Price
	%tbody
		- @orders.each do |order, orderlines|
			- orderlines.each do |orderline|
				%tr
					%td= order
					%td= orderline[0]
					%td= orderline[1]
					%td= orderline[2]

:javascript
	$(document).ready(function() {
		$('#index').DataTable({
			order: [[0, 'dsc']],
			rowGroup: {
				dataSrc: 0
			},
			scrollY:        500,
			deferRender:    true,
			scroller:       true,
			search: false
		});
	});

app/views/main/show_timetable.html.haml
%p
	.row.align-items-end.mb-5.justify-content-center
		.col-lg-3.col-md-5.col-sm-12
			= image_tag "#{@movie.name}.jpg", height: 300 
		.col-lg-9.col-md-7.col-sm-12.mt-3
			.fs-2
				= @movie.name
			= render "movieCardDetail"

%p
	- @timetables.each do |theater, timetables|
		- if timetables.length != 0	
			- @empty = false
			%h5.mt-5="Cinema: #{theater}"
			.row.justify-content-start
				- timetables.each do |timetable|
					.col-lg-1.col-md-2.col-sm-3
						= button_to "#{timetable.time_start.strftime("%H:%M")}", buyticket_path, method: "post", params: {timetable: timetable}, class: 'btn btn-info mt-2'
	- if @empty
		.fs-4
			not showing today, please come back later
%p
	= button_to "back", main_path, class: "btn btn-secondary btn-lg mt-5", method: "get"